const path = {
  admin: {
    dashboards: '/dashboards',
    courses: '/courses',
    newCourse: '/courses/new',
    posts: '/posts',
    newPosts: '/posts/new',
    transaction: '/transaction',
    transactionHistory: '/transaction/history',
    statistics: '/statistics',
    profiles: '/profiles',
    categorys: '/categorys',
    Articlecategorys: '/categorys/article',
    Coursecategorys: '/categorys/course',
  },
  client: {
    auth: {
      login: '/auth/login',
      register: '/auth/register',
    },
    learning: '/learning',
    learningPath: '/learning-path',
    learningPathDetail: '/learning-path-detail',
    courses: '/courses',
    logAuth: 'log-auth',
    news: '/news',
    newsDetail: '/news-detail',
    contact: '/contact',
    profile: '/profile',
    setting: '/setting',
    newPost: '/new-post',
    myPost: '/my-post',
    bookmark: '/me/bookmark',
  },
};
export default path;
